import AdminComponent from "@/components/AdminComponent";
import { Metadata } from "next";
import "./../../app/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ProductForm from "@/components/ProductForm";
import { Product } from "@/lib/types";
import { createProducts } from "@/services/products.service";
import Button from "@/components/Button";
import CreateComponent from "@/components/CreateComponent";

export const metadata: Metadata = {
    title: "Tienda Misita | Admin",
    description: "Generated by create next app",
};

const handleCreate = async (product: Omit<Product, 'id'>) => {
    await createProducts(product);
    window.location.reload();
  };

export default function Create() {
    return (
        <div className="adm-create-section">
            <Header />
            <CreateComponent />
            <Footer />
        </div>
    )
}