import ClientComponent from "@/components/ClientComponent";
import { Metadata } from "next";
import "./../app/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Tienda Misita | Admin",
    description: "Generated by create next app",
};
export default function Client() {
    return (
        <div>
            <Header />
            <ClientComponent />
            <Footer />
        </div>
    )
}